name: Set Version
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set env
      run: echo "APP_VERSION=v-0.0.15" >> $env:GITHUB_ENV
    - name: Test
      run: echo $APP_VERSION
